name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: macos
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
        - build: win64-msvc
          os: windows-latest
          rust: stsable-x86_64-gnu
          target: x86_64-pc-windows-msvc
        - build: win64-gnu
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Build applications
      shell: bash
      run: |
        CARGO_PROFILE_RELEASE_STRIP=symbols ${{ env.CARGO }} build \
          --verbose \
          --target ${{ matrix.target }} \
          --all-features \
          --release \
          -p cggtts-cli
        ls -lah target/${{ matrix.target }}/release
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          bin="target/${{ matrix.target }}/release/cggtts-cli.exe"
        else
          bin="target/${{ matrix.target }}/release/cggtts-cli"
        fi
        echo "BIN=$bin" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        echo "ARCHIVE=cggtts-cli-${{ github.ref_name }}-${{ matrix.target }}" >> $GITHUB_ENV

    - name: Creating directory for archive
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"
        cp "$BIN" "$ARCHIVE"/
        cp {README.md,LICENSE-MIT,LICENSE-APACHE} "$ARCHIVE"/

    - name: Gzip archive (Unix)
      shell: bash
      if: matrix.os != 'windows-latest'
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
        echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV
    
    - name: Zip archive (Windows)
      shell: bash
      if: matrix.os == 'windows-latest'
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        echo "ASSET=$ARCHIVE.zip" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.zip.sha256" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3     
      with:
        name: ${{ env.ASSET }}
        path: |
          ${{ env.ASSET }}
          ${{ env.ASSET_SUM }}
  
  release:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/create-release@v1
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}

    - name: Download linux-stable
      uses: actions/download-artifact@v3
      with: 
        name: cggtts-cli-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz

    - name: Upload linux-stable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cggtts-cli-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
        asset_name: cggtts-cli-x86_x64-linux-gnu.tar.gz
        asset_content_type: application/gzip

    - name: Download macos-latest
      uses: actions/download-artifact@v3
      with: 
        name: cggtts-cli-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz

    - name: Upload macos-latest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cggtts-cli-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
        asset_name: cggtts-cli-x86_64-apple-darwin.tar.gz
        asset_content_type: application/gzip
    
    - name: Download macos-latest (aarch64)
      uses: actions/download-artifact@v3
      with: 
        name: cggtts-cli-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz

    - name: Upload macos-latest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cggtts-cli-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz
        asset_name: cggtts-cli-aarch64-apple-darwin.tar.gz
        asset_content_type: application/gzip

    - name: Download windows x86_64 (msvc)
      uses: actions/download-artifact@v3
      with: 
        name: cggtts-cli-${{ github.ref_name }}-x86_64-pc-windows-msvc.zip       
    
    - name: Download windows x86_64 (msvc)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cggtts-cli-${{ github.ref_name }}-x86_64-pc-windows-msvc.zip  
        asset_name: cggtts-cli-x86_64-pc-windows-msvc.zip  
        asset_content_type: application/zip
  
    - name: Download windows x86_64 (gnu)
      uses: actions/download-artifact@v3
      with: 
        name: cggtts-cli-${{ github.ref_name }}-x86_64-pc-windows-gnu.zip
        
    - name: Download windows x86_64 (msvc)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cggtts-cli-${{ github.ref_name }}-x86_64-pc-windows-gnu.zip  
        asset_name: cggtts-cli-x86_64-pc-windows-gnu.zip 
        asset_content_type: application/zip
